# Generated by Django 4.2.7 on 2024-08-16 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='datosUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesion', models.CharField(blank=True, max_length=48, null=True)),
                ('nroCelular', models.CharField(blank=True, max_length=16, null=True)),
                ('perfilUsuario', models.CharField(blank=True, max_length=256, null=True)),
                ('usuarioRelacionado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
