# Generated by Django 4.2.7 on 2024-08-14 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDepartamento', models.CharField(blank=True, max_length=48, null=True)),
                ('descripcionDepartamento', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
