# Generated by Django 4.2.7 on 2024-08-14 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=32, null=True)),
                ('apellido', models.CharField(blank=True, max_length=32, null=True)),
                ('numero', models.CharField(blank=True, max_length=24, null=True)),
                ('email', models.CharField(blank=True, max_length=48, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
